name: strike_force_heroes_3
description: "A new strike_force_heroes_3 project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 4.0.1+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter_plus: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
icons_launcher:
  image_path: 'assets/512.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true